server.port = 3000
spring.application.name = products
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/incidentresponse
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql: true
management.endpoints.web.exposure.include=info, health, mappings